services:
  mongo:
    image: mongo:5.0
    container_name: dev-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  ktor:
    image: my-ktor-app:latest
    container_name: dev-ktor
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
