# MongoDB Host1
#mongo.host1.url=localhost
mongo.host1.url=host.docker.internal
mongo.host1.port=27017

# MongoDB Host2 ()
#mongo.host2.url=milg002
#mongo.host2.port=27017

# MongoDB Host3 ()
#mongo.host3.url=milg003
#mongo.host3.port=27017

# Replica Set Name (replSet)
#mongo.replicaSetName=myReplicaSet

# Database Name
mongo.database=p30a
